# Generated by Django 5.1.4 on 2025-01-14 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('brand', models.CharField(max_length=20)),
                ('quantity', models.IntegerField()),
                ('product_description', models.CharField(max_length=400)),
                ('product_price', models.CharField(max_length=4)),
                ('product_image', models.FileField(upload_to='images/')),
                ('product_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new_app.seller')),
            ],
        ),
    ]
