# Generated by Django 5.1.4 on 2025-01-25 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0002_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_data', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='new_app.customer')),
                ('product_data', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='new_app.product')),
            ],
        ),
    ]
