# Generated by Django 5.1.4 on 2025-02-03 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0004_buy_now'),
    ]

    operations = [
        migrations.CreateModel(
            name='pay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_no', models.CharField()),
                ('cvv', models.CharField()),
                ('expiry_date', models.DateField()),
                ('buy', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='new_app.buy_now')),
            ],
        ),
    ]
