# Generated by Django 5.1.4 on 2025-02-12 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0005_pay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pay',
            name='buy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new_app.buy_now'),
        ),
    ]
